"""Add queued user guidance for running jobs.

Revision ID: add_job_guidance
Revises: add_cost_token_categories
Create Date: 2026-07-29 17:00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "add_job_guidance"
down_revision: str | None = "add_cost_token_categories"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the owner-scoped FIFO guidance queue."""
    op.create_table(
        "job_guidance",
        sa.Column(
            "job_id",
            sa.UUID(),
            nullable=False,
            comment="Job that should receive this guidance",
        ),
        sa.Column(
            "author_id",
            sa.UUID(),
            nullable=False,
            comment="Owner who submitted this guidance",
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=False,
            comment="Owner-provided idea to include in the running investigation",
        ),
        sa.Column(
            "submitted_during_iteration",
            sa.Integer(),
            nullable=False,
            comment="Job iteration that was active when the guidance was queued",
        ),
        sa.Column(
            "delivered_iteration",
            sa.Integer(),
            nullable=True,
            comment="Iteration whose completed turn received this guidance",
        ),
        sa.Column(
            "delivered_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the frozen guidance item was marked delivered",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
            comment="UUIDv7 primary key generated by PostgreSQL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Timestamp when record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_guidance_author_id"),
        "job_guidance",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_guidance_job_id"),
        "job_guidance",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        "ix_job_guidance_pending_fifo",
        "job_guidance",
        ["job_id", "created_at", "id"],
        unique=False,
        postgresql_where=sa.text("delivered_at IS NULL"),
    )

    op.execute("ALTER TABLE job_guidance ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE job_guidance FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY job_guidance_all_owner ON job_guidance FOR ALL
            USING (
                EXISTS (
                    SELECT 1
                    FROM jobs
                    WHERE jobs.id = job_guidance.job_id
                      AND jobs.owner_id::text =
                          current_setting('app.current_user_id', TRUE)
                )
            )
            WITH CHECK (
                EXISTS (
                    SELECT 1
                    FROM jobs
                    WHERE jobs.id = job_guidance.job_id
                      AND jobs.owner_id::text =
                          current_setting('app.current_user_id', TRUE)
                )
                AND author_id::text = current_setting('app.current_user_id', TRUE)
            )
        """
    )

    op.execute("GRANT ALL ON job_guidance TO openscientist_app")
    op.execute("GRANT ALL ON job_guidance TO openscientist_admin")


def downgrade() -> None:
    """Remove queued job guidance."""
    op.execute("DROP POLICY IF EXISTS job_guidance_all_owner ON job_guidance")
    op.drop_index("ix_job_guidance_pending_fifo", table_name="job_guidance")
    op.drop_index(op.f("ix_job_guidance_author_id"), table_name="job_guidance")
    op.drop_index(op.f("ix_job_guidance_job_id"), table_name="job_guidance")
    op.drop_table("job_guidance")
